select FIRST_HALF.FLAVOR
from FIRST_HALF, ICECREAM_INFO
where TOTAL_ORDER > 3000 and FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR and ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
order by TOTAL_ORDER DESC;